### PR TITLE
Setup projects with Oomph

### PR DESCRIPTION
**Pull request by attiand**
I have tried to setup Wildfly Hive with [Oomph](https://projects.eclipse.org/projects/tools.oomph). However Hive does not recognize Wildfly Swarm projects setup by Oomph. If I delete the project and import it as a Maven project from the UI it is detected as i should. 

The problem is that the ClasspathChangeListener never gets a classpath changed event during the Oomph Maven import process. I had to add IJavaElementDelta.F_CONTENT to get it to analyse the new project.

I have attached a simple Oomph setup project that shows the problem [swarm.setup.gz](https://github.com/fbricon/wildfly-hive/files/1446876/swarm.setup.gz)

### CODE REVIEW

**Comment by fbricon** [comment]
I haven't touched to this project in such a long time I expected it to be completely stale when used against recent swarm releases :-) So, thanks for your interest @attiand! 

Right off the bat, I'd say adding IJavaElementDelta.F_CONTENT seems dubious since this means the detection job would be triggered on any java file content change. I need to double check if it's causing any trouble.

**Comment by attiand** [comment]
I think its awesome, simple configuration and fits perfectly in an automated setup with Oomph. I think the problem is that the project does not yet recognized its Java nature when the change event is fired. I have updated the fix to use a Maven project changed listener but even now the project has not yet a Java nature so I had to use the Maven project packaging type.

**Comment by fbricon** [comment]
-1 on relying on m2e's ProjectChangeListener.

The current detection solution is build-tool agnostic, and should support Gradle (at least in theory, I haven't tried).

Have you tried detecting new project event, for oomph?

**Comment by fbricon** [comment]
so I tried the oomph setup 3 times without that PR, it failed twice, but detection works once. So there's probably a race condition at some point. I have been unable to run the oomph setup from an hosted eclipse instance (project is not imported), so it's hard to figure out what's happening exactly.

**Comment by attiand** [comment]
Yes I agree, I also tried to register a listener with IWorkspace but the ADDED event for the project may or may not come before it has its Java nature.

If I simply add `IJavaElementDelta.ADDED` to `ClasspathChangeListener#isClasspathChanged` it works for a single Maven project. But I guess the ADDED event gets lost for children projects if the parent project is not a Java project (In my case the Maven POM project)

To debug I have configured EclipseIniTask so I am able to remote debug during the startup phase. However it takes a lot of time :-(

```xml
  <setupTask
      xsi:type="setup:EclipseIniTask"
      option="-agentlib:jdwp="
      value="transport=dt_socket,server=y,address=8000,suspend=n"
      vm="true"/>
```
Here is how Oomph imports a Maven project: http://git.eclipse.org/c/oomph/org.eclipse.oomph.git/plain/plugins/org.eclipse.oomph.setup.maven/src/org/eclipse/oomph/setup/maven/impl/MavenImportTaskImpl.java

**Comment by attiand** [comment]
Unfortunately could not find a reliable solution. When I get some time I will try to call the analyser from a Oomph plugin, or simply setup a Lunch configuration.

**Comment by fbricon** [comment]
I think there's definitely room for wildfy-hive to improve detection on startup, even without oomph, since I have always experienced (rare) cases when detection was failing. I believe the oomph use case is just exacerbating the issue.

**Pull request closed without merging**
